##
# Basic

# The title of your website
site_title: Cr0ydon's Blog
# A boolean (true or false) indicating whether URL rewriting is forced
rewrite_url: true                  


##
# Theme

# The name of your custom theme
theme: historia


##
# Content

# Pico's default date format;
# See https://php.net/manual/en/function.strftime.php for more info
date_format: "%d %B %Y"
# Change how Pico sorts pages ("alpha" for alphabetical order, "date", or "meta")
pages_order_by: date               
# Sort pages in ascending ("asc") or descending ("desc") order
pages_order: asc                 

##
# Custom

custom_html_head_content: '<link rel="me" href="https://mastodon.social/@croydon">Mastodon</a>'

# Note im Footer
footnote: "© Cr0ydon"
icon_png: "/assets/general/icon/icon.png"


# Link Tree
link_tree:
    github:
      display: GitHub
      url: https://github.com/Croydon
    gitlab:
      display: GitLab
      url: https://gitlab.com/Cr0ydon
    linked:
      display: LinkedIn
      url: https://www.linkedin.com/in/cr0ydon/
      alt_icon: linkedin
    rss:
      display: RSS
      url: https://blog.cr0ydon.com/feed
      alt_button: default
    firefox:
      display: Firefox Add-ons
      url: https://addons.mozilla.org/firefox/user/4788738/
      alt_icon: browser-firefox
      alt_button: reddit
