on: [push,]
name: "Generate Blog"

jobs:
  generate-blog:
    name: "Generate Blog"
    runs-on: ubuntu-22.04
    steps:
    - name: "Checkout Blog Content"
      uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - name: "Generate Static Export"
      uses: devcontainers/ci@v0.2
      with:
        runCmd: ./var/www/html/.devcontainer/staticCreate.sh
    - name: "Deploy 🚀"
      run: |
        mkdir ../export
        cp -r static/* ../export/
        git fetch
        git checkout gh-pages
        git config --global user.email "bot@cr0ydon.com"
        git config --global user.name "CroydonBot"
        rm -rf ./*
        cp -r ../export/* ./ 
        git add -A
        now="$(date +'%Y-%m-%d %H:%M:%S')"
        git commit -am "Export $now" 
        git push
