on: [push,]
name: "Generate Blog"

jobs:
  generate-blog:
    name: "Generate Blog"
    runs-on: ubuntu-22.04
    steps:
    - name: "Checkout Blog Content"
      uses: actions/checkout@v4
      with:
        path: "blog"
        fetch-depth: "0"
    - name: "Checkout Static Content"
      uses: actions/checkout@v4
      with:
        ref: "gh-pages"
        path: "pages"
        fetch-depth: "0"
    - name: "Generate Static Export"
      uses: devcontainers/ci@v0.3
      with:
        subFolder: "blog"
        runCmd: /var/www/html/.devcontainer/staticCreate.sh
    - name: "Deploy 🚀"
      run: |
        rm -r pages/*
        cp -r blog/static/* pages/
        cd pages/
        git config --global user.email "bot@cr0ydon.com"
        git config --global user.name "CroydonBot"
        ls -la
        git add -A
        now="$(date +'%Y-%m-%d %H:%M:%S')"
        git diff-index --quiet HEAD || git commit -am "Export $now" 
        git push
